version: 2.1

orbs:
  maven: circleci/maven@1.4.1

workflows:
  maven_test:
    jobs:
      - maven/test:
          command: make b
          executor:
            name: maven/default
            tag: '3.9-eclipse-temurin-25'
          pre-steps:
            - run:
                name: Build
                command: mvn -B -DskipTests clean package
