logging.level.root=TRACE
logging.level.org.springframework=OFF
logging.level.org.apache=OFF
logging.level.org.jesperancinha.spring=TRACE
logging.level.org.jesperancinha.spring.old.webapp.model=TRACE
logging.level.org.jesperancinha.spring.controller=TRACE